### ISSUE TITLE
Problem with the order of the annotations in the tiers

### ISSUE THREAD

**Issue by bertoky** [dopefishh/pympi#7]
Hi (I'm here again, I'm sorry...),

I have found another issue, when I do simply:

eaf = pympi.Elan.Eaf(input_file)

eaf.to_file (output_file)

input_file and output_file have not the same order in the annotations in the tiers so it triggers that when I use the add_ref_annotation() method, there are some values that are repeated incorrectly.

Thank you so much.

**Comment by dopefishh** [comment]
Thanks for the response, don't be sorry, this is really valuable.
I'll check this asap(probably next monday)

**Comment by dopefishh** [comment]
I've tested the functions with some sample eaf files but I can't seem to reproduce the problem. Can you send me a non functioning eaf in which it doesn't work?

**Comment by bertoky** [comment]
Yes, for instance with this eaf file, when I do:

eaf = pympi.Elan.Eaf(input_file)

eaf.to_file (output_file)

The tier "Trad_inic" has their values in different order, and the same with others.

File: https://dl.dropboxusercontent.com/u/5544264/input_file.eaf

Thank you

**Comment by dopefishh** [comment]
Hmm, I'm still not sure what the problem is. The reference annotation do indeed appear in a different order in the XML output but the xml tags are not ordered and that's not a constraint of the file so when opening the file in Elan they are equal.
Can you show in a small example(for example sample code) how it affects your data?

**Comment by bertoky** [comment]
Hi again,

I left you another input file: https://dl.dropboxusercontent.com/u/5544264/input_file_dope.eaf

And the source code: https://dl.dropboxusercontent.com/u/5544264/dope.py

You maybe have to change the lines with path of input/output files, anyway I guess you could check that in the output file, in the tier with ID = MD_Cat2, there are two ANNOTATION_REF="a5807" instead of one "a5808" and another "a5807".

I think that it could be for the reasons I told you before, I couldn't reach another explanation...

Thank you so much.

**Comment by dopefishh** [comment]
Hi Bertoky,

Thanks for the feedback. I think I have found the problem.
If I change line 32 to:
```python
eaf.add_ref_annotation(tier, tier_ref, tuplanueva[0]+1, tuplanueva[3])
```
It works. This is because two annotations match the original time point `tuplanueva[0]`. When multiple annotations match the timepoint the first one gets chosen. A way to circumvent this is to add 1ms to the timepoint or take the middle. I'll make a note in the documentation about this in the next release version.

Thanks again for the feedback!

Best,
Mart

ps. The safe and clean way would be then to change line 32 to:
```python
eaf.add_ref_annotation(tier, tier_ref, (tuplanueva[0]+tuplanueva[1])/2, tuplanueva[3])
```

**Comment by bertoky** [comment]
Hi again,

I understand, for this case it works properly, but unfortunately this is only an example, in my whole eaf, my arrays are bigger than these and I don't know where will be the timepoints, so I guess that there is no way to do it with big arrays, do you understand what I mean?

Thank you so much.

**Comment by dopefishh** [comment]
This really shouldn't be a problem with larger files. Just add ref annotations to the middle time point instead of the start. If you do find problems please let me know.
Best,
Mart

**Comment by bertoky** [comment]
Yes, you are right, I tested it and it worked properly,

Thank you so much man!

**Comment by dopefishh** [comment]
Good to hear!
Let me know if you have any furthur issues or features you want to see in the library.

Best,
Mart
